### PR TITLE
Add unix socket listening support

### PR DESCRIPTION
**Pull request by robvanoostenrijk**
This adds support for saml-auth-proxy to listen on a unix socket instead of TCP port.

If `SAML_PROXY_BIND` has a format of `unix:/var/run/saml-auth-proxy.sock`, a unix socket will be created instead.

Because unix sockets require a clean shutdown of the network connection (`listener.close`), this also adds a [errgroup](https://pkg.go.dev/golang.org/x/sync/errgroup) wrapper to clean up on shutdown.

### CODE REVIEW

**Comment by itzg** [comment]
Out of curiosity, what are some scenarios for listening on Unix sockets?

**Comment by robvanoostenrijk** [comment]
I run saml-auth-proxy, as well as the authenticated application as docker containers in a docker-compose setup.
nginx runs on the main host routing into different dockerized applications.

However, I don't want to expose additional TCP ports to other applications on the same host. Unix sockets allow only processes with the correct permissions to connect.

Relevant nginx configuration for saml-auth-proxy:
```
	location /saml/ {
		proxy_pass		http://unix:/var/run/saml-auth-proxy/saml-auth-proxy.sock;

		proxy_set_header	Host			$host;
		proxy_set_header	X-Real-IP		$remote_addr;
		proxy_set_header	X-Auth-Request-Redirect	$request_uri;

		location = /saml/auth {
			internal;
			proxy_pass		http://unix:/var/run/saml-auth-proxy/saml-auth-proxy.sock;

	                # nginx auth_request includes headers but not body
       		        proxy_set_header        Content-Length          "";
	          	proxy_pass_request_body off;
		}

		location = /saml/acs {
			proxy_pass		http://unix:/var/run/saml-auth-proxy/saml-auth-proxy.sock;

			more_set_headers -s 302 "Location: /code/";
		}
	}
```

**Comment by itzg** [comment]
Awesome!

**Comment by robvanoostenrijk** [comment]
Adding sample application configuration as well, for people looking for it in the future.

This protects [code-server](https://github.com/coder/code-server) docker deployment with saml-auth-proxy over nginx:

```
	location /code/ {
		auth_request /saml/auth;

                # 401: 302 redirect into /saml/sign_in
		error_page 401 =302 /saml/sign_in;
		proxy_pass		http://unix:/var/run/code-server/code-server.sock:/;

		proxy_http_version	1.1;
		proxy_set_header	X-Forwarded-For		$proxy_add_x_forwarded_for;
		proxy_set_header	Host			$http_host;
		proxy_set_header	Upgrade			$http_upgrade;
		proxy_set_header	Connection		"upgrade";
		proxy_redirect		off;
	}

```

**Comment by itzg** [comment]
FYI merge conflict from other PR. BTW, I greatly appreciate you splitting up the PRs especially since it causes a little more housekeeping for you like this.

**Review by itzg — APPROVED** [review]

**Comment by itzg** [comment]
Included in https://github.com/itzg/saml-auth-proxy/releases/tag/1.15.0

**Pull request merged**
